using System;
using System.Linq;

using P_Arcade.Models;

namespace P_Arcade.Games
{
    internal class CopyADrawing : Game
    {
        /// <summary>
        /// Copy A Drawing constructor
        /// </summary>
        public CopyADrawing() : base("Copy A Drawing", false) { }

        private const byte VAL_DRAWING_WIDTH = 11;
        private const byte VAL_DRAWING_HEIGHT = 11;

        private static readonly Random rnd = new Random();

        private static readonly (int X, int Y) Origin = (VAL_DRAWING_HEIGHT / 2, VAL_DRAWING_WIDTH / 2);

        private static (int X, int Y) Cursor;

        private static bool[,] tab_blnCurrentDrawing;
        private static bool[,] tab_blnGoalDrawing;

        public override string[] About()
        {
            string[] tab_strAbout =
            {
                "Copy A Drawing is a puzzle game where the goal is to recreate a randomly generated target drawing",
                "The target is displayed on the right side of the screen, and your canvas is on the left",

                "",

                "Each drawing is generated by connecting random points with straight lines to form a closed shape",
                "Every round presents a unique challenge because each drawing is unique",

                "",

                "Move your cursor around the canvas using the arrow keys or WASD",
                "Press Space, Enter, Q or E to toggle the selected cell on or off",
                "Filled cells are white, and empty cells show a checkerboard pattern to help distinguish them",
                "Your cursor is highlighted in cyan to make it easy to track",

                "",

                "The game ends as soon as your drawing matches the target exactly",
                "Press R at any time to discard the current drawing and start over with a new target",
                "Press Escape to quit to the menu"
            };

            return tab_strAbout;
        }

        public override void Start()
        {
            bool blnRestart;

            do
            {
                blnRestart = false;

                InitializeGame();

                Arcade.ShowTitle(Name);

                Console.CursorVisible = false;

                do
                {
                    // Reset cursor position so the grid is redrawn in-place
                    Console.SetCursorPosition(0, 5);

                    DrawGrid();

                    ConsoleKey movementKeyPressed = Console.ReadKey(true).Key;

                    ConsoleKey[] tab_MovementKeys =
                    {
                        ConsoleKey.UpArrow,
                        ConsoleKey.DownArrow,
                        ConsoleKey.LeftArrow,
                        ConsoleKey.RightArrow,

                        ConsoleKey.W,
                        ConsoleKey.A,
                        ConsoleKey.S,
                        ConsoleKey.D
                    };

                    ConsoleKey[] tab_PlaceKeys =
                    {
                        ConsoleKey.Spacebar,
                        ConsoleKey.Enter,
                        ConsoleKey.Q,
                        ConsoleKey.E
                    };

                    if (tab_MovementKeys.Contains(movementKeyPressed))
                    {
                        MoveCursor(movementKeyPressed);
                    }
                    else if (tab_PlaceKeys.Contains(movementKeyPressed))
                    {
                        ToggleCurrentCell();
                    }
                    else if (movementKeyPressed == ConsoleKey.R)
                    {
                        // Flag restart and break out of gameplay loop immediately
                        blnRestart = true;
                        break;
                    }
                    else if (movementKeyPressed == ConsoleKey.Escape)
                    {
                        // Exit the entire game loop
                        return;
                    }

                    // Continue until player successfully matches the target drawing
                } while (!DrawingsMatch());

                // If the player requested a restart, skip success screen and reinitialize
                if (blnRestart)
                    continue;

                Arcade.ShowTitle(Name);
                DrawGrid();

                Console.WriteLine("\n   You matched the drawings!");
                Console.ReadKey(true);

            } while (blnRestart);
        }

        /// <summary>
        /// Reset the game state
        /// </summary>
        private static void InitializeGame()
        {
            Cursor = Origin;

            tab_blnCurrentDrawing = new bool[VAL_DRAWING_HEIGHT, VAL_DRAWING_WIDTH];

            // Safety precaution to stop instant wins from ever happening
            do
                tab_blnGoalDrawing = GenerateRandomDrawing();
            while (DrawingsMatch());
        }

        /// <summary>
        /// Toggle the currently selected cell
        /// </summary>
        private static void ToggleCurrentCell()
        {
            int x = Cursor.X;
            int y = Cursor.Y;

            tab_blnCurrentDrawing[x, y] = !tab_blnCurrentDrawing[x, y];
        }

        /// <summary>
        /// Restricts an integer value to a specified inclusive range
        /// If the value is below the minimum, returns the minimum
        /// If above the maximum, returns the maximum
        /// Otherwise, returns the original value
        /// </summary>
        /// <param name="intValue">The input value to clamp.</param>
        /// <param name="intMin">The lower bound of the allowed range.</param>
        /// <param name="intMax">The upper bound of the allowed range.</param>
        /// <returns>The clamped value within min and max</returns>
        private static int Clamp(int intValue, int intMin, int intMax)
        {
            if (intValue < intMin)
                return intMin;

            if (intValue > intMax)
                return intMax;

            return intValue;
        }

        /// <summary>
        /// Move around the drawing grid
        /// </summary>
        private static void MoveCursor(ConsoleKey keyPressed)
        {
            switch (keyPressed)
            {
                case ConsoleKey.UpArrow:
                case ConsoleKey.W:
                    Cursor = (Cursor.X - 1, Cursor.Y);
                    break;

                case ConsoleKey.DownArrow:
                case ConsoleKey.S:
                    Cursor = (Cursor.X + 1, Cursor.Y);
                    break;

                case ConsoleKey.LeftArrow:
                case ConsoleKey.A:
                    Cursor = (Cursor.X, Cursor.Y - 1);
                    break;

                case ConsoleKey.RightArrow:
                case ConsoleKey.D:
                    Cursor = (Cursor.X, Cursor.Y + 1);
                    break;
            }

            int x = Clamp(Cursor.X, 0, VAL_DRAWING_HEIGHT - 1);
            int y = Clamp(Cursor.Y, 0, VAL_DRAWING_WIDTH - 1);

            Cursor = (x, y);
        }
        /// <summary>
        /// Check if both drawings match
        /// </summary>
        private static bool DrawingsMatch()
        {
            for (byte bytRow = 0; bytRow < VAL_DRAWING_HEIGHT; bytRow++)
                for (byte bytCol = 0; bytCol < VAL_DRAWING_WIDTH; bytCol++)
                    if (tab_blnCurrentDrawing[bytRow, bytCol] != tab_blnGoalDrawing[bytRow, bytCol])
                        return false;

            return true;
        }

        /// <summary>
        /// Renders a single cell in the drawing grid
        /// </summary>
        /// <param name="blnFilled">Whether or not the cell is full</param>
        /// <param name="intRow">The row index</param>
        /// <param name="intCol">The column index</param>
        /// <param name="blnSelected">Whether or not the current cell has been selected</param>
        /// <param name="blnPlayerGrid">Whether or not this is the board that the player uses</param>
        private static void DrawCell(bool blnFilled, int intRow, int intCol, bool blnSelected, bool blnPlayerGrid)
        {
            string strCellContent = "  ";

            ConsoleColor backgroundColor;
            ConsoleColor foregroundColor = ConsoleColor.Black;

            // Draw the cell either filled in or with a checker patern
            if (blnFilled)
                backgroundColor = ConsoleColor.White;
            else
                backgroundColor = (intRow + intCol) % 2 == 0 ? ConsoleColor.Black : ConsoleColor.DarkGray;

            // Render differently when the cursor is selecting something
            if (blnSelected && blnPlayerGrid)
            {
                strCellContent = "[]";

                // Highlight cursor differently depending on whether the cell is already filled
                if (blnFilled)
                    backgroundColor = ConsoleColor.Cyan;
                else
                {
                    foregroundColor = ConsoleColor.White;
                    backgroundColor = ConsoleColor.DarkCyan;
                }
            }

            Console.BackgroundColor = backgroundColor;
            Console.ForegroundColor = foregroundColor;

            Console.Write(strCellContent);

            Console.ResetColor();
        }

        /// <summary>
        /// Draw both the player's current drawing and the target drawing side-by-side,
        /// along with a small instruction panel on the right.
        /// </summary>
        private static void DrawGrid()
        {
            string strHorizontal = new string('═', VAL_DRAWING_WIDTH * 2);

            string[] tab_strInstructions =
            {
                "Instructions:",
                "Move with Arrow Keys or WASD",
                "Press Space, Enter, Q or E to fill in a tile",
                "Match the right drawing",
                "Press R for a new drawing",
                "Press ESC to quit"
            };

            int intDrawingWidth = VAL_DRAWING_WIDTH * 2 + 2;

            string strLeftTitle = "YOUR DRAWING";
            string strRightTitle = "TARGET";

            // Centers each title within its respective drawing box width
            string strLeftHeader = strLeftTitle.PadLeft((intDrawingWidth + strLeftTitle.Length) / 2).PadRight(intDrawingWidth);

            string strRightHeader = strRightTitle.PadLeft((intDrawingWidth + strRightTitle.Length) / 2).PadRight(intDrawingWidth);

            Console.WriteLine($"  {strLeftHeader} {strRightHeader}");
            Console.WriteLine();
            Console.WriteLine($"  ╔{strHorizontal}╗ ╔{strHorizontal}╗");

            for (byte bytRow = 0; bytRow < VAL_DRAWING_HEIGHT; bytRow++)
            {
                Console.Write("  ║");

                for (byte bytCol = 0; bytCol < VAL_DRAWING_WIDTH; bytCol++)
                {
                    bool blnSelected = bytRow == Cursor.X && bytCol == Cursor.Y;
                    bool blnPainted = tab_blnCurrentDrawing[bytRow, bytCol];

                    DrawCell(blnPainted, bytRow, bytCol, blnSelected, true);
                }

                Console.Write("║ ║");

                for (byte bytCol = 0; bytCol < VAL_DRAWING_WIDTH; bytCol++)
                {
                    bool blnGoalFilled = tab_blnGoalDrawing[bytRow, bytCol];

                    DrawCell(blnGoalFilled, bytRow, bytCol, false, false);
                }

                Console.Write("║");

                // Aligns instruction lines with corresponding grid rows (if available)
                if (bytRow < tab_strInstructions.Length)
                    Console.Write("\t" + tab_strInstructions[bytRow]);

                Console.WriteLine();
            }

            Console.WriteLine($"  ╚{strHorizontal}╝ ╚{strHorizontal}╝");
        }

        /// <summary>
        /// Generate a random target drawing
        /// </summary>
        private static bool[,] GenerateRandomDrawing()
        {
            bool[,] tab_blnDrawing = new bool[VAL_DRAWING_HEIGHT, VAL_DRAWING_WIDTH];

            int intPoints = rnd.Next(3, 12);

            (int X, int Y) posStart = Origin;

            for (int i = 0; i < intPoints; i++)
            {
                (int X, int Y) posEnd = (rnd.Next(VAL_DRAWING_HEIGHT), rnd.Next(VAL_DRAWING_WIDTH));

                DrawLine(tab_blnDrawing, posStart, posEnd);

                // Clears the endpoint so it doesn't remain part of the final shape
                tab_blnDrawing[posEnd.X, posEnd.Y] = false;

                posStart = posEnd;
            }

            // Close the shape by connecting the last random point back to the origin
            DrawLine(tab_blnDrawing, posStart, Origin);

            return tab_blnDrawing;
        }

        /// <summary>
        /// Draws a straight line between two points using Bresenham's algorithm.
        /// This produces clean, uniform lines without diagonal bias.
        /// </summary>
        private static void DrawLine(bool[,] tab_blnDrawing, (int X, int Y) posStart, (int X, int Y) posEnd)
        {
            int intDeltaX = Math.Abs(posEnd.X - posStart.X);
            int intDeltaY = Math.Abs(posEnd.Y - posStart.Y);

            int intStepX = posStart.X < posEnd.X ? 1 : -1;
            int intStepY = posStart.Y < posEnd.Y ? 1 : -1;

            int intError = intDeltaX - intDeltaY;

            while (true)
            {
                // Mark current pixel
                tab_blnDrawing[posStart.X, posStart.Y] = true;

                // Stop if we reached destination
                if (posStart.X == posEnd.X && posStart.Y == posEnd.Y)
                    break;

                int intDoubleError = 2 * intError;

                // Horizontal step
                if (intDoubleError > -intDeltaY)
                {
                    intError -= intDeltaY;
                    posStart.X += intStepX;
                }

                // Vertical step
                if (intDoubleError < intDeltaX)
                {
                    intError += intDeltaX;
                    posStart.Y += intStepY;
                }
            }
        }
    }
}